# mongodb configuration
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
      database: ${MONGODB_DATABASE}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}